### ISSUE TITLE
python omxplayer wrapper

### ISSUE THREAD

**Issue by willprice** [Douglas6/omxcontrol#1]
Hi,

Have you seen my project `python-omxplayer-wrapper`
https://github.com/willprice/python-omxplayer-wrapper
It's extremely similar to yours, perhaps we could team up?

**Comment by Douglas6** [comment]
Will, I had not seen that, and I thought I had googled pretty extensively. Wish I had, or I wouldn't have bothered with this project. They do look similar, tho yours is better documented. I'm not sure how active I'll be supporting mine. I'll put a link to your project in the README, and update my post on raspberrypi.org/forums to point folks to yours.

Please feel free to lift anything out of here if you find it useful, maybe the listX methods?

**Comment by willprice** [comment]
Hi Douglas,

Yes it's a shame, we both have seem to have implemented pretty much the same thing! Thanks for the offer of using your source code. I'll have a look over the weekend and see whether I can pinch some ideas ;)

Cheers
